### ISSUE TITLE
[Result-list] Show features and their attributes in a table

### ISSUE THREAD

**Issue by antoniave** [open-pioneer/trails-openlayers-base-packages#11]
As a user I want to see the attributes of a set of features in a **table** like visualization in the result-list. 

As a user I want to be able to **select** and deselect (single) features in the table by click (e.g. using a checkbox). 
As a user I want to **select** all features in the list be clicking a single control (e.g. button). 
As a user I want to **deselect** all selected features by clicking a single control (e.g. button). 

As a user I want to be able to **sort** the table contents based on the attributes in a column. 
As a user I want to be able to see the columns in an appropriate **width**. 

As a developer I want to be able to specify one or more **attributes that are not shown** in the list. 

Acceptance criteria: 
- the result-list UI contains a **table** that can visualize a set of feature attributes
  - the list must be **scrollable** (no pagination needed)
  - it is desirable that the user can modify the column width (does not need to be implemented if complex) 
- the **data** shown in the list are received from #10 
  - if the list does already contain data, the existing data is discarded and the new data is shown in the list 
  - if the incoming data collection is empty, an empty table or fallback text is shown 
  - the following data types of attributes must be supported: string (also quite long strings), number, date, boolean; no special formatting is needed for the data types (handled in #241)
- the **metadata** received from #10 is be used to implement the following requirements:
  -  **column headers** are created using the attribute names specified
    - only the attributes mentioned in the header metadata are shown in the table (other attributes in the features are not shown / **filtered** ) 
    - the **order of the columns** is specified by the order of the attribute names in the metadata
    - the **column width** specified in the metadata is applied to the columns of the table (this is not needed if the user can resize the cells and the table can determine initial useful column widths) 
- **selection** of features: 
  - the user can select and deselect single features in the table (e.g. checkbox); if a feature is selected, other features are _not_ automatically deselected
  - the user can select all features in the table by clicking a single control (e.g. button)
  - the user can deselect all selected features in the table by clicking a single control (e.g. button)
- the user can **sort** the table according to the values of attributes in a column
  - when sorting, all values are treated as strings despite from number, date and booleans
  - null/undefined values in the data must be handled during sorting 
- the **documentation** contains a hint that not more than XXX features (number needs to be specified depending on performance; maybe a few hundred) should be loaded into the result-list; the limit does not need to be implemented in the list, the app developer has to care about that

Implementation idea: https://tanstack.com/table/v8/docs/adapters/react-table, https://chakra-ui.com/getting-started/with-react-table

Out of scope: 
- text search for attribute values
- show data from multiple data sources at once 
- additive selection

**Comment by mbeckem** [comment]
PR: https://github.com/open-pioneer/trails-openlayers-base-packages/pull/275

**Comment by SvenReissig** [comment]
Fixed column resizing bug (id source had invalid characters).

**Comment by dpayk** [comment]
Tested and adjusted docu -> OK
