### ISSUE TITLE
[Result-list] Show a highlight for all listed features in the map

### ISSUE THREAD

**Issue by antoniave** [open-pioneer/trails-openlayers-base-packages#14]
As a user I want to see a graphic highlight for all features in the result-list table. 

Acceptance criteria: 
- If any data is displayed in the result-list table, the corresponding geometries of the features are shown as graphic highlights in the map. 
- The highlight should be independent from other highlight in the map. For example, result-list highlights should not be removed if a search is performed or a search result is deleted. However, it is desirable to use the highlight logic implemented in the MapModel (needs to be adjusted). 

Out of scope: 
- highlighting of hovered features
- highlight style configurable
- highlighting of selected features (see #15)

Info: Zoom ist handled in #240

**Comment by mbeckem** [comment]
- highlightOptions must be configurable via props
- it must be possible to disable highlights completely

**Comment by ChristophMaskos** [comment]
PR [295](https://github.com/open-pioneer/trails-openlayers-base-packages/pull/295)
