### ISSUE TITLE
[Result-list] Interface for getting all selected features

### ISSUE THREAD

**Issue by antoniave** [open-pioneer/trails-openlayers-base-packages#17]
As a developer I want to receive information about features selected in the result-list table to be able to trigger additional functions for the set of selected features. 

Acceptance criteria: 
- the result-list provides a public interface for requesting information about all selected features
- the interface must return all selected feature objects with all their attributes --> output data exactly looks like the input data (see #10)
  - add hint in documentation: if the developer needs information about the origin (e.g. source layer) of the features, they need to add these information to the feature objects before passing them to the result-list (see #10 ). 

Implementation hint: useful to implement together with #18

**Comment by mbeckem** [comment]
With #18, the result list will inform the developer about any change in the user's selection. This requirement can be easiliy implemented by tracking the selection state:

```jsx
function MyComponent() {
  // This example uses local state, but `selectedFeatures` can also live in some shared location
  const [selectedFeatures, setSelectedFeatures] = useState([]);
  return <ResultList onSelectionChange={(event) => setSelectedFeatures(event.features)} />;
}
```

This way, the developer knows at all times the set of selected features.
