### ISSUE TITLE
[Result-list] Event on selection change

### ISSUE THREAD

**Issue by antoniave** [open-pioneer/trails-openlayers-base-packages#18]
As a developer I want to receive information if the selection within the table of the result-list changes to be able to react on this (e.g. hiding or disabling additional features that work with the current selection: see #17 and #19 )

Acceptance criteria: 
- if the selection changes, the result-list informs about the change, e.g. by calling a callback function that is provided in the component props
- the event contains information about the type of change (selection changed)
- the event must contain information about the currently selected features (Array of Features)

Implementation hint: useful to implement together with #17

**Comment by mbeckem** [comment]
Note: to make the API easier to work with the selection event will now transport an array of _features_ instead of ids. The array of ids will be made accessible via a convenience method on the event (e.g. `event.getFeatureIds()`).
