### ISSUE TITLE
[Result-list] Event on data changed

### ISSUE THREAD

**Issue by antoniave** [open-pioneer/trails-openlayers-base-packages#234]
As a developer I want to receive information if the data within the table of the result-list changes to be able to react on this (e.g. hiding or showing the result-list).

Acceptance criteria:

- if data is added to or removed from the table, the result-list informs about the change , e.g. by calling a callback function that is provided in the component props

- the event contains information about the type of change ("added" or "removed")
- the event should also contain information about the (updated) number of features contained in the table

**Comment by dpayk** [comment]
This is no longer valid, because a developer has to control visibility and content themselves already and thus knows when they change.
