### ISSUE TITLE
[Spatial selection] Show no-drop cursor only on map

### ISSUE THREAD

**Issue by bierett** [open-pioneer/trails-openlayers-base-packages#254]
If the selected source for the spatial selection isn't available, the cursor will change from `default|pointer` to `no-drop`.
If the cursor is e.g. on the overview map or toc, the cursor is still `no-drop`.

![Image](https://github.com/open-pioneer/trails-openlayers-base-packages/assets/3016561/d42fcef2-a08a-46b3-b299-5bd7aca02dfa)

We want to show the `no-drop` cursor only on the map, not on all other UI elements.

**Comment by mbeckem** [comment]
Resolved by #333
