### ISSUE TITLE
[Sample Apps] Create a component showcase

### ISSUE THREAD

**Issue by mbeckem** [open-pioneer/trails-openlayers-base-packages#301]
The current [Demo](https://open-pioneer.github.io/trails-demo/openlayers-base-packages/samples/map-sample/?lang=de) is getting too cluttered with too many components.

Our idea is to create a "Component Showcase" App that contains multiple views, one per demonstrated component or feature. 
The user can then select the desired view from a menu, the application's UI will update as a result.

The existing demo application should be stripped down, but it should be kept to serve as an example for new projects (file layout, component interactions, ...).

Note: the resulting showcase should look good on small and large screens (responsive, text wrapping, ...)

**Comment by antoniave** [comment]
Planned views: 
- TOC + Basemapswitcher + Legend
- Coordinate-Viewer
- Scale-Viewer
- Scale-Bar
- Measurement
- Editing
- Map-Navigation
- Geolocation 
- Spatial Bookmarks
- Overview Map
- Printing
- Selection + Result List
- Search + Highlight

**Comment by mbeckem** [comment]
Sample app pr: https://github.com/open-pioneer/trails-openlayers-base-packages/pull/329
