### ISSUE TITLE
[MapModel] Introduce types attributes and "Union"-Type for layers

### ISSUE THREAD

**Issue by mbeckem** [open-pioneer/trails-openlayers-base-packages#305]
Currently layer in the layer model do not have a attribute that can be used to determine the type of a layer (e.g. SimpleLayer, WMSLayer, ...). It would be helpful to introduce an attribute on the layer that specifies its type. 

Additionally, it would be helpful to introduce a union type for layers that allows Typescript narrowing. Currently all layer types depend on a type, which is used in cases where multiple layer types (kinds) are allowed. However, it is not possible to narrow the layer type.

**Comment by mbeckem** [comment]
Note: the resulting union(s) should become the "official" `Layer` / `Sublayer` type. The current one would be something like a "base type" instead.

**Comment by antoniave** [comment]
PR: https://github.com/open-pioneer/trails-openlayers-base-packages/pull/352
