### ISSUE TITLE
[Spatial selection] Automatically select selection-source

### ISSUE THREAD

**Issue by antoniave** [open-pioneer/trails-openlayers-base-packages#310]
The spatial selection UI provides the possibility to select a selection source that will be used during the selection. 
Currently, no selection source is selected if the UI is shown initially. The user needs to choose one their self. 

It would be very helpful if the first selection-source would be automatically selected.

**Comment by mbeckem** [comment]
Idea for implementation:
- During mount (or if sources change):
   - select the first source (even if not available) _if no other source is currently selected_
   - If a source is currently selected, attempt to keep it selected (if still present); if that is not possible, go into state "no sources selected"
- Note: fix the error tooltip if no sources are selected (its currently the same as if a source is unavailable)

**Comment by mbeckem** [comment]
PR: #346
