### ISSUE TITLE
[TOC] No way to identify the Layer hierarchy with the use of a screenreader or any other assistive technology

### ISSUE THREAD

**Issue by julkuh** [open-pioneer/trails-openlayers-base-packages#321]
### Issue description

Possible solutions might be [WCAG Treeview Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/) or [WCAG Grouped Listbox Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/examples/listbox-grouped/).

### Validations

- [X] Read and follow our [code of conduct](https://github.com/open-pioneer/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [contributing guidelines](https://github.com/open-pioneer/trails-starter/blob/main/docs/Contributing.md)
- [X] Check that there isn't already a similar issue

**Comment by mbeckem** [comment]
PR: #340
