### ISSUE TITLE
When using the search input's result list, there is no relation between results and the topic they belong to

### ISSUE THREAD

**Issue by julkuh** [open-pioneer/trails-openlayers-base-packages#322]
### Issue description

When using the search input's result list, there is no relation between result items and the topic they belong to. Because of the missing semantic relation between result items and topics, screenreader users have no chance to identify relevant results in an efficient way.

I think a solution could be to group the results in a div with _role="group"_ and an _aria-labelledby_ that refers to the _id_ of the topic's title similiar to the [WCAG Sample for a tree Navigation](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-navigation/)

### Validations

- [X] Read and follow our [code of conduct](https://github.com/open-pioneer/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [contributing guidelines](https://github.com/open-pioneer/trails-starter/blob/main/docs/Contributing.md)
- [X] Check that there isn't already a similar issue

**Comment by mbeckem** [comment]
PR: #341
