### ISSUE TITLE
Move attribution according to the map view's padding

### ISSUE THREAD

**Issue by antoniave** [open-pioneer/trails-openlayers-base-packages#339]
### Issue description

The attributions are shown on the OpenLayers map. However, their positioning does not consider the map view's padding. As the map view's padding is usually used if something covers the map, the attribution is likely to be covered by those elements. 

Hence, the attribution should be moved according to the map view's padding. 

### Validations

- [X] Read and follow our [code of conduct](https://github.com/open-pioneer/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [contributing guidelines](https://github.com/open-pioneer/trails-starter/blob/main/docs/Contributing.md)
- [X] Check that there isn't already a similar issue

**Comment by mbeckem** [comment]
Idea: Set css variables based on the map view's current padding (i.e. `--map-padding-top` etc.)  in the `<MapContainer />` component.
Also add a default css rule that positions the attribution based on the current `--map-padding-bottom`.

**Comment by antoniave** [comment]
Branch feature/move-attribution

**Comment by antoniave** [comment]
PR: #364
