### ISSUE TITLE
[Zoom] Respect zoom limits

### ISSUE THREAD

**Issue by artmarks** [open-pioneer/trails-openlayers-base-packages#356]
### Issue description

# Issue description

The current Zoom-component doesn't completely respect the zoom / scale limits if set.

1. When zoom limits are set, and the user is in the max / min zoom level, the Zoom-component trys to zoom in / out further and cancels its anitmation, whichs leads to a wobbling in and out effect on the map.
2. If the user should only be able to zoom to the given resolutions, (with `constrainResolution: true` in the `MapConfigProviderImpl`), the user can "cheat" in between, if the zoom button is clicked while it is still animating.

# Reproduce

## Example configuration in MapConfigProviderImpl

```jsx

{
	initialView: {
	  kind: "position",
	  center: { x: 404747, y: 5757920 },
	  zoom: 14
	},
	advanced: {
	  view: {
		maxZoom: 15,
		minZoom: 13,
                constrainResolution: true
	  },
	},
	layers: [
	  new SimpleLayer({
		  title: "OSM",
		  isBaseLayer: true,
		  olLayer: new TileLayer({
			  source: new OSM()
		  })
	  })
	]
};

```

Try the showcase demo `mapNavigation`

### Validations

- [X] Read and follow our [code of conduct](https://github.com/open-pioneer/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [contributing guidelines](https://github.com/open-pioneer/trails-starter/blob/main/docs/Contributing.md)
- [X] Check that there isn't already a similar issue

**Comment by mbeckem** [comment]
PR: #357

**Comment by dpayk** [comment]
The only disadvantage is that you can't zoom in quickly by clicking the button like crazy. But I think that's ok.
