### ISSUE TITLE
Map printing

### ISSUE THREAD

**Issue by ThomasEverding** [open-pioneer/trails-openlayers-base-packages#37]
As a user I want to download the current map view as a printable file. The printed map preserves the current map scale.

Acceptance criteria:
 - The printing function can be started by a button.
 - The printing provides a file for download (PNG and PDF).
 - The printing is performed client side.
 - A GUI must be provided to specify the file format and a title.
 - The printed file contains the map view as an image.
   - If file format is PNG, the current map canvas is exported as an image.
   - If file format is PDF, the map is printed as a DIN A4 landscape PDF, preserving the current map scale and showing the current map center in the middle of the exported map image.
 - The printed map contains a scale-bar.
 - The title is shown at the top center in a header area above the map (both in PNG and PDF).

Open Layers examples: 
- https://openlayers.org/en/latest/examples/print-to-scale.html 
- https://openlayers.org/en/latest/examples/export-map.html

**Comment by senait8991** [comment]
PR #277

**Comment by mathe05** [comment]
> Further requirements are:
> 
>   * Selection of print templates (e. g. for different page formats like landscape/portrait and DIN A4, DIN A3, ..)
>   * Selection of print resolution (e. g. 96/150/300 DPI)
>   * Display the print frame in the map (user can select print view by pan/zoom the map within the print frame)
>   * Selection if map scale should be keep or selection of map scale

https://github.com/open-pioneer/trails-openlayers-base-packages/pull/601 implements these requirements, except for these:

>   * Adding custom title and comment/description to print document
>   * Selection if legend should be included
>   * Selection if copyright informations should be included
