### ISSUE TITLE
[Feature editing] Edit feature geometries

### ISSUE THREAD

**Issue by ThomasEverding** [open-pioneer/trails-openlayers-base-packages#41]
As a user I want to change the geometry of a feature.

As a developer I want to start the edit feature process for a given feature. 

Acceptance criteria:
 - In general, supported **geometry-types** are **polygon and multi-polygon**
 - The developer can call a method/interface that starts the edit feature process for a given feature.
   - Parameters: Feature to edit or it's ID and a reference to the feature's layer (OGC API Features Service integrated as VectorLayer). 
 - The geometry is highlighted in the map.
 - The vertices of the geometry can be dragged to a new position to change the geometrie's shape.
 - Intermediate points between the vertices can be dragged to a new position. This results in a new vertex at this position.
 - The map can be panned and zoomed while editing.
 - The user is able to cancel the editing (e.g. by pressing ESC)
 - When the user finishes the drawing (e.g. by double click or pressing enter on the keyboard or clicking somewhere outside the geometry) , the changed geometry is stored in the OGC API Feature Service (only Xtra Proxy needs to be tested - add hint in documentation that only Xtra Proxy was tested).
 - If the editing is completed (and the geometry is stored) or cancelled, a kind of response (return value/ event /callback function) is provided. This response has to contain the information if the editing was successful, the ID of the edited feature and the ID/the reference of/to the corresponding layer.
 - The Demo App contains a test tools which allows the user to select a feature on a layer (hard coded) in the map and starts the edit process for the selected feature. 

out of scope:
 - Other service types than OGC API Feature Services
 - Other geometry types than polygons/multi-polygons
 - Snapping
 - Attribute editing
 - Rotate / rescale feature

**Comment by bierett** [comment]
PR: #289
