### ISSUE TITLE
[Feature editing] Create new features

### ISSUE THREAD

**Issue by ThomasEverding** [open-pioneer/trails-openlayers-base-packages#42]
As a user I want to create new polygon features.
As a developer I want to start the edit feature process for a specific layer.

Acceptance criteria:
- The developer can call a method/interface that starts the create new feature process for a given layer.
  - Parameters: The layer (OGC API Features Service integrated as VectorLayer) the created feature will be stored in.
- The user can draw a polygon on the map by clicking at the desired vertex positions.
  - The user must be able to cancel the editing (e.g. by pressing ESC)
  - The map can be panned and zoomed while editing.
- After finalizing the drawing (e.g. by double click or pressing enter on the keyboard or clicking somewhere outside the polygon) 
  - the polygon is closed 
  - attributes are filled with dummy/default values
  - the feature is stored in the OGC API Feature layer (only Xtra Server needs to be tested - add hint in documentation that only Xtra Server was tested)
  - the drawing/editing process is stopped (if the drawing should remain active, the developer needs to start the create process again)
- If the creation is completed (and the geometry is stored) or cancelled, a kind of response (return value/ event /callback function) is provided. This response has to contain the information if the editing was successful, the ID of the edited feature and the ID/the reference of/to the corresponding layer.
- The app contains a test tool which allows the user to create a feature in a layer (hard coded). 

out of scope:
 - Other service types than OGC API Feature Services
 - Other geometry types than polygons
 - Snapping
 - Attribute editing

**Comment by bierett** [comment]
PR: #282
