### ISSUE TITLE
Coordinate search

### ISSUE THREAD

**Issue by bierett** [open-pioneer/trails-openlayers-base-packages#70]
As a user I want to zoom to given coordinates by typing them into a search field.

Acceptance criteria:

- The GUI consists of a search field (text input), a control to reset the coordinate search
- The GUI may also need controls to select the coordinate system of the given coordinates
- The GUI can be placed at a placeholder in the app
- Coordinates were transformed, if the map and coordinate system are not equal
- The map is centered to the coordinates
- ~~A marker is placed to the coordinates~~
- ~~Markers from previous searches are removed~~
- ~~When the coordinate search is reset, the marker is removed~~

**Comment by antoniave** [comment]
The coordinate search has been implemented (https://github.com/open-pioneer/trails-openlayers-base-packages/pull/355). However, the following criteria have not been implemented: 

- A marker is placed to the coordinates
- Markers from previous searches are removed
- When the coordinate search is reset, the marker is removed

The marker handling can be done in a project as the developer is informed if a coordinate search is conducted.
