### ISSUE TITLE
Scale selection

### ISSUE THREAD

**Issue by bierett** [open-pioneer/trails-openlayers-base-packages#72]
As a developer I want to configure a list with selectable scales.
As a user I want to select a scale from a pre-configured list to zoom in/out the map.

Acceptance criteria:

- A developer can configured multiple scales in the package
- Scales are visible in and selectable from the list
- The GUI can be placed at a placeholder in the app
- The GUI consists of a select box which contains a list of all configured scales
- After selecting a scale, the list is closed / hidden and the map scale synchronized with it
- The scale viewer #24 is updated too

Hint:
While zooming the map (mousewheel, zoom in/out buttons, etc.) the scale selection is synchronized with the actual scale.

**Comment by mbeckem** [comment]
PR: #332
