### ISSUE TITLE
[Map Navigation] Forward / Backward view

### ISSUE THREAD

**Issue by bierett** [open-pioneer/trails-openlayers-base-packages#81]
As a user I want to navigate backwards and forwards in the maps view.

Acceptance criteria:

- The GUI consists of a button to navigate backwards and one button to navigate forwards the maps view
- The GUI can be placed at a placeholder in the app
- By clicking "backwards" the maps view is reset to the previous maps view
- By clicking "forwards" the maps view is reset to the last maps view

Hint:

- There is no limit how many views can restore or reset by the user
- Only the maps extent and zoom-level will be restored
- Change of layer selection has no affect

**Comment by mbeckem** [comment]
PR: #365
